### ISSUE TITLE
Running failure with an error

### ISSUE THREAD

**Issue by wang3702** [robpearc/DeepFoldRNA#1]
Thank you for your excellent work! I am trying to run your program on our clusters. I followed all your instructions for installment and running. However, I encountered the following error now:
```
Traceback (most recent call last):
  File "runDeepFoldRNA.py", line 452, in <module>
    run_prediction(args.input_dir,args.generate_all_models)
  File "runDeepFoldRNA.py", line 190, in run_prediction
    model = network_1.Pred_Network(device)
  File "/net/kihara/scratch/wang3702/DeepFoldRNA/network/network_1.py", line 20, in __init__
    self.input_embedder = embedders.Input_Embedder(network_config,network_config["input_embedder"],device)
  File "/net/kihara/scratch/wang3702/DeepFoldRNA/network/embedders.py", line 29, in __init__
    self.pos_1 = self.compute_position_1(device)
  File "/net/kihara/scratch/wang3702/DeepFoldRNA/network/embedders.py", line 34, in compute_position_1
    rel_pos = ((pos[:,None] & (1 << torch.arange(self.rel_pos_1d)))) > 0
TypeError: unsupported operand type(s) for <<: 'int' and 'Tensor'
```
Could you please have  a check to see how to fix it? Thank you so much for your kind help!

**Comment by wang3702** [comment]
We fixed this to run by changing "<<" to "<". Please also modify on your code.

**Comment by robpearc** [comment]
What python/pytorch versions are you using? There should be scripts included to download the compatible versions of both in the scripts directory. Try installing the conda version locally and calling the program by python3 runDeepFoldRNA.py --input_dir <path_to_input_dir>. "<<" is the bit left shift operator and is not equivalent to "<".

**Comment by wang3702** [comment]
Thanks for your quick reply! My pytorch version is 1.7.0. I have changed back to run again. I have reinstalled the environment to see if it works or not.

**Comment by wang3702** [comment]
I tried installing the environment again. It raised the same error.

**Comment by leeyang** [comment]
change Line 34 into
`rel_pos = ((pos[:,None] & (1 << np.arange(self.rel_pos_1d)))) > 0`
works for me.

**Comment by wang3702** [comment]
@leeyang Thank you so much! It works for me too.
